{
 "title": "Conso Elec",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "prix_kwh_hp", "label": "Prix kW/h", "query": "18.41" },
   { "name": "prix_kwh_hc", "label": "Prix kW/h HC", "query": "14.70" },
   { "name": "prix_kwh_normal", "label": "Prix kW/h tarif normal", "query": "17.40" }
  ]
 },
 "panels": [
  {
   "title": "Tarif en cours",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "PTEC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tarif Bleu HC Période",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "alias": "HP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HCHC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*$prix_kwh_hc*0.00001" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tarif HP Période",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "alias": "HP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HCHP",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*$prix_kwh_hp*0.00001" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total HC + HP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expression": "($A*$prix_kwh_hc*0.00001+$B*$prix_kwh_hp*0.00001) ",
     "type": "math"
    }
   ]
  },
  {
   "title": "Tarif normal indicatif",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expression": "($A+$B) *$prix_kwh_normal*0.00001",
     "type": "math"
    }
   ]
  },
  {
   "title": "Répartition HC / HP",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "alias": "Heures Pleines",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HCHP",
     "query": "SELECT mean(\"value\") *$prix_kwh_hp*0.00001 FROM \"HCHP\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Heures creuses",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HCHC",
     "query": "SELECT mean(\"value\") *$prix_kwh_hc*0.00001 FROM \"HCHC\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Intensité Instantanée",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "IINST",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Puissance apparente instantanée",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kvoltamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "PAPP",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Index Heure Creuse",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "HCHC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Index Heure Pleine",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "HCHP",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expression": "$A+$B", "type": "math" }
   ]
  },
  {
   "title": "Consommation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Heures Pleines",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "HCHP",
     "query": "SELECT mean(\"value\")::integer AS value FROM \"HCHC\" WHERE $timeFilter GROUP BY time(1s) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       }
      ]
     ]
    },
    {
     "alias": "Heures Creuses",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "HCHC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Intensité (Ampere)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "alias": "Intensite (A)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "IINST",
     "query": "SELECT mode(\"value\") FROM \"IINST\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Index Heures creuses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Index HC",
     "measurement": "HCHC",
     "query": "SELECT mean(\"value\")::integer AS value FROM \"HCHC\" WHERE $timeFilter GROUP BY time(1s) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Puissance apparente (KvA)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kvoltamp" } },
   "targets": [
    {
     "alias": "Puissance apparente (kVA)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PAPP",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Index Heures pleines",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Index HP",
     "measurement": "HCHP",
     "query": "SELECT mean(\"value\")::integer AS value FROM \"HCHC\" WHERE $timeFilter GROUP BY time(1s) fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}